# Created with package:mono_repo v6.2.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.2.2
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze; PKG: a; `dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:a;commands:command_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:a
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: a_pub_upgrade
        name: a; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: a
        run: dart pub upgrade
      - name: "a; dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart analyze"
        if: "always() && steps.a_pub_upgrade.conclusion == 'success'"
        working-directory: a
        run: "dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart analyze"
  job_003:
    name: "analyze; PKG: b; `dart pub global activate melos && dart pub global run melos bootstrap --scope b && dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:b;commands:command_3"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:b
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: b_pub_upgrade
        name: b; flutter pub pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: b
        run: flutter pub pub upgrade
      - name: "b; dart pub global activate melos && dart pub global run melos bootstrap --scope b && dart analyze"
        if: "always() && steps.b_pub_upgrade.conclusion == 'success'"
        working-directory: b
        run: "dart pub global activate melos && dart pub global run melos bootstrap --scope b && dart analyze"
  job_004:
    name: "format; PKG: a; `dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:a;commands:command_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:a
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: a_pub_upgrade
        name: a; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: a
        run: dart pub upgrade
      - name: "a; dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.a_pub_upgrade.conclusion == 'success'"
        working-directory: a
        run: "dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart format --output=none --set-exit-if-changed ."
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "format; PKG: b; `dart pub global activate melos && dart pub global run melos bootstrap --scope b && dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:b;commands:command_4"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:b
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: b_pub_upgrade
        name: b; flutter pub pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: b
        run: flutter pub pub upgrade
      - name: "b; dart pub global activate melos && dart pub global run melos bootstrap --scope b && dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.b_pub_upgrade.conclusion == 'success'"
        working-directory: b
        run: "dart pub global activate melos && dart pub global run melos bootstrap --scope b && dart format --output=none --set-exit-if-changed ."
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "test; PKG: a; `dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:a;commands:command_2"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:a
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: a_pub_upgrade
        name: a; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: a
        run: dart pub upgrade
      - name: "a; dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart test"
        if: "always() && steps.a_pub_upgrade.conclusion == 'success'"
        working-directory: a
        run: "dart pub global activate melos && dart pub global run melos bootstrap --scope a && dart test"
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
  job_007:
    name: "test; PKG: b; `dart pub global activate melos && dart pub global run melos bootstrap --scope b && flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:b;commands:command_5"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:b
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: b_pub_upgrade
        name: b; flutter pub pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: b
        run: flutter pub pub upgrade
      - name: "b; dart pub global activate melos && dart pub global run melos bootstrap --scope b && flutter test"
        if: "always() && steps.b_pub_upgrade.conclusion == 'success'"
        working-directory: b
        run: "dart pub global activate melos && dart pub global run melos bootstrap --scope b && flutter test"
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
